version: '3.8'

services:
  code-runner-server:
    image: coderunner-server:latest
    environment:
      - APP_MODE=server
      - APP_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    ports:
      - "7979:7979"
      - "50011:50011"
    restart: unless-stopped
