// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: tokenIssuer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenIssuer_GenerateToken_FullMethodName = "/codeRunner.v1.tokenIssuer/GenerateToken"
)

// TokenIssuerClient is the client API for TokenIssuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenIssuerClient interface {
	GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
}

type tokenIssuerClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenIssuerClient(cc grpc.ClientConnInterface) TokenIssuerClient {
	return &tokenIssuerClient{cc}
}

func (c *tokenIssuerClient) GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTokenResponse)
	err := c.cc.Invoke(ctx, TokenIssuer_GenerateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenIssuerServer is the server API for TokenIssuer service.
// All implementations must embed UnimplementedTokenIssuerServer
// for forward compatibility.
type TokenIssuerServer interface {
	GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error)
	mustEmbedUnimplementedTokenIssuerServer()
}

// UnimplementedTokenIssuerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenIssuerServer struct{}

func (UnimplementedTokenIssuerServer) GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}
func (UnimplementedTokenIssuerServer) mustEmbedUnimplementedTokenIssuerServer() {}
func (UnimplementedTokenIssuerServer) testEmbeddedByValue()                     {}

// UnsafeTokenIssuerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenIssuerServer will
// result in compilation errors.
type UnsafeTokenIssuerServer interface {
	mustEmbedUnimplementedTokenIssuerServer()
}

func RegisterTokenIssuerServer(s grpc.ServiceRegistrar, srv TokenIssuerServer) {
	// If the following call pancis, it indicates UnimplementedTokenIssuerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenIssuer_ServiceDesc, srv)
}

func _TokenIssuer_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenIssuerServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenIssuer_GenerateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenIssuerServer).GenerateToken(ctx, req.(*GenerateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenIssuer_ServiceDesc is the grpc.ServiceDesc for TokenIssuer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenIssuer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codeRunner.v1.tokenIssuer",
	HandlerType: (*TokenIssuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateToken",
			Handler:    _TokenIssuer_GenerateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tokenIssuer.proto",
}
