server:
  etcd:
    endpoints: "8.154.36.180:2378"
    key: "/services/code-runner"
  grpc:
    host: "8.154.36.180"
    port: "50011"
  app:
    host: "0.0.0.0"
    port: "7979"

client:
  server:
    host: "8.154.36.180"
    port: "7979"
    path: "codeRunner/ws"
  app:
    weight: 1